/*
 * This source file was generated by the Gradle 'init' task
 */
package javaproject;

import javaproject.config.RateLimiterConfig;
import javaproject.middlewares.IRateLimiterMiddleware;
import javaproject.middlewares.LeakyBucketRateLimiterMiddleware;
import javaproject.utils.RandomDelayGenerator;

public class App {
    private static RateLimiterConfig config = new RateLimiterConfig(5, 1);
    private static String clientId = "test-client";
    public static void main(String[] args) {
    IRateLimiterMiddleware rateLimiter = new LeakyBucketRateLimiterMiddleware(config);
    for (int i = 0; i < 7; i++) {
        boolean allowed = rateLimiter.isRequestAllowed(clientId);
        RandomDelayGenerator.delay(250, 300);
    }
    }
}
